
package es.ies;

import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.List;

import es.ies.modeloTxtDB.FileManager;

/**
 *
 * @author Jorge
 */
public class FrmTiendaApp extends javax.swing.JFrame {

    /**
     *El constructor crea el frame y el fichero para recordar los datos.
     */
    public FrmTiendaApp() {
//jdbc:oracle:thin:@localhost:1521:XE [tienda on Default schema]

        File f = new File("credenciales.txt");
        Lector lec = new Lector(f);

        ImageIcon img = new ImageIcon("usuario.png");
        setIconImage(img.getImage());
        setLocationRelativeTo(null);
        setTitle("Iniciar Sesión");
        initComponents();

        if (f.exists()) {
            String usr = "";
            String pass = "";
            String str = lec.verContenido();

            int indice = 0;
            for (int i = 0; i < str.length(); i++) {
                if (str.charAt(i) == '!') {
                    indice = i;
                }
            }
            usr = str.substring(0, indice);
            pass = str.substring(indice + 1, str.length());
            txtUsuario.setText(usr);
            txtPass.setText(pass);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTienda = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        chkRecordar = new javax.swing.JCheckBox();
        txtPass = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        btnVerPass = new javax.swing.JToggleButton();
        lblUsuario = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        btnDejar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(350, 50, 0, 0));
        setIconImage(getIconImage());
        setResizable(false);

        pnlTienda.setBackground(new java.awt.Color(255, 255, 255));
        pnlTienda.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pnlTiendaPropertyChange(evt);
            }
        });
        pnlTienda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pnlTiendaKeyPressed(evt);
            }
        });

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/ies/img/usuario.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setText(" INICIAR SESIÓN");

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(119, 158, 203));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLogin.setText("ENTRAR");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });

        chkRecordar.setBackground(new java.awt.Color(204, 204, 204));
        chkRecordar.setText(" Recuérdame");
        chkRecordar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRecordarActionPerformed(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });

        btnRegistrar.setText("Registrarse");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnVerPass.setText("ver");
        btnVerPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPassActionPerformed(evt);
            }
        });

        lblUsuario.setText("Usuario");

        lblPass.setText("Contraseña");

        btnDejar.setText("Dejar de recordarme");
        btnDejar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDejarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTiendaLayout = new javax.swing.GroupLayout(pnlTienda);
        pnlTienda.setLayout(pnlTiendaLayout);
        pnlTiendaLayout.setHorizontalGroup(
            pnlTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTiendaLayout.createSequentialGroup()
                .addGroup(pnlTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTiendaLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(pnlTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTiendaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnDejar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTiendaLayout.createSequentialGroup()
                            .addGroup(pnlTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlTiendaLayout.createSequentialGroup()
                                    .addGap(69, 69, 69)
                                    .addGroup(pnlTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblPass)
                                        .addComponent(lblUsuario))
                                    .addGap(18, 18, 18)
                                    .addGroup(pnlTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlTiendaLayout.createSequentialGroup()
                                            .addComponent(chkRecordar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(71, 71, 71)
                                            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(pnlTiendaLayout.createSequentialGroup()
                                    .addGap(222, 222, 222)
                                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnVerPass)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnLimpiar))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlTiendaLayout.setVerticalGroup(
            pnlTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTiendaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblImagen)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(pnlTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addGap(18, 18, 18)
                .addGroup(pnlTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addGroup(pnlTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkRecordar)
                    .addComponent(btnRegistrar))
                .addGap(50, 50, 50)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDejar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTienda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed


    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered

        btnRegistrar.setToolTipText("Si usted no tiene cuenta haga clic aquí");

    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered

        btnLogin.setToolTipText("Clic aquí para entrar");


    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnVerPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPassActionPerformed

        if (btnVerPass.isSelected()) {
            txtPass.setEchoChar((char) 0);
        } else {
            txtPass.setEchoChar('*');
        }

    }//GEN-LAST:event_btnVerPassActionPerformed

    private void chkRecordarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRecordarActionPerformed

        if (chkRecordar.isSelected()) {

            File f = new File("credenciales.txt");
            Escritor esc = new Escritor(f);

            StringBuffer sb = new StringBuffer();
            sb.append(txtUsuario.getText());
            sb.append('!');
            char pass[] = txtPass.getPassword();
            for (int i = 0; i < pass.length; i++) {
                sb.append(pass[i]);
            }
            String cadena = sb.toString();

            esc.escribe(cadena);
        }


    }//GEN-LAST:event_chkRecordarActionPerformed
/**
 * 
 * @param evt 
 * Conecta con la bbdd y comprueba para hacer el login
 */


private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {
    int i = 0;
    String user = null;
    String pass;
    StringBuffer sb = new StringBuffer();
    char passw[] = txtPass.getPassword();
    for (int j = 0; j < passw.length; j++) {
        sb.append(passw[j]);
    }
    String password = sb.toString();

    FileManager fileManager = new FileManager();
    List<String> users = fileManager.readUsers();
    if (users != null) {
        boolean salir = false;
        for (String line : users) {
            String[] parts = line.split(",");
            user = parts[0];
            pass = parts[1];
            if (user.equals(txtUsuario.getText()) && pass.equals(password)) {
                if (user.contains("admin") && password.contains("2019")) {
                    i = 2;
                    fileManager.writeUser("nombreAdmin.txt", user);
                    salir = true;
                } else {
                    i = 1;
                    fileManager.writeUser("nombreCli.txt", user);
                    salir = true;
                }
            } else {
                i = 0;
            }
            if (salir) break;
        }
    }

    if (i == 1) {
        pnlTienda pnlT = new pnlTienda();
        pnlT.setSize(582, 602);
        pnlTienda.removeAll();
        pnlTienda.add(pnlT);
        pnlTienda.revalidate();
        pnlTienda.repaint();
        setTitle("Tienda Cliente: " + user);
    } else if (i == 2) {
        pnlTiendaAdmin pnlT = new pnlTiendaAdmin();
        pnlT.setSize(582, 602);
        pnlTienda.removeAll();
        pnlTienda.add(pnlT);
        pnlTienda.revalidate();
        pnlTienda.repaint();
        setTitle("Tienda Administrador: " + user);
    } else {
        JOptionPane.showMessageDialog(null, "Usuario o Contraseña incorrectos", "Error",
                JOptionPane.INFORMATION_MESSAGE);
    }
}
//GEN-LAST:event_btnLoginActionPerformed
/**
 * 
 * @param evt 
 * Muestra el panel de registro.
 */
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        pnlEntrarRegistrar pnl2 = new pnlEntrarRegistrar();
        pnl2.setSize(582, 602);
        pnlTienda.removeAll();
        pnlTienda.add(pnl2);
        pnlTienda.revalidate();
        pnlTienda.repaint();
        setTitle("Registro");
    }//GEN-LAST:event_btnRegistrarActionPerformed
/**
 * 
 * @param evt 
 * Borra el fichero y los campos, deja de recordar al usuario.
 */
    private void btnDejarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDejarActionPerformed

        File f = new File("credenciales.txt");
        f.delete();
        txtUsuario.setText("");
        txtPass.setText("");
    }//GEN-LAST:event_btnDejarActionPerformed

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed

    }//GEN-LAST:event_btnLoginKeyPressed

    private void pnlTiendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnlTiendaKeyPressed

    }//GEN-LAST:event_pnlTiendaKeyPressed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLogin.doClick();
        }
    }//GEN-LAST:event_txtPassKeyPressed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLogin.doClick();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtUsuario.setText("");
        txtPass.setText("");
        btnVerPass.setEnabled(false);

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void pnlTiendaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pnlTiendaPropertyChange
      
    }//GEN-LAST:event_pnlTiendaPropertyChange

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
            btnVerPass.setEnabled(true);
    }//GEN-LAST:event_txtUsuarioFocusLost

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTiendaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTiendaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTiendaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTiendaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new FrmTiendaApp().setVisible(true);
            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDejar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JToggleButton btnVerPass;
    private javax.swing.JCheckBox chkRecordar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlTienda;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
