package es.ies;

import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class pnlEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form pnlEmpleado
     */
    Empleado emple = new Empleado();

    /**
     *
     */
    public pnlEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerPass = new javax.swing.JToggleButton();
        lblPass3 = new javax.swing.JLabel();
        txtPass2 = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        lblUsuario2 = new javax.swing.JLabel();
        lblPass2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        lblDir = new javax.swing.JLabel();
        txtTlf = new javax.swing.JTextField();
        lblDir1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDir2 = new javax.swing.JLabel();
        txtPuesto = new javax.swing.JTextField();
        lblDir3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbSeo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        btnVerPass.setText("ver");
        btnVerPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPassActionPerformed(evt);
            }
        });

        lblPass3.setText("Repetir contraseña");

        txtPass2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPass2FocusLost(evt);
            }
        });
        txtPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass2ActionPerformed(evt);
            }
        });

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        lblUsuario2.setText("Usuario");

        lblPass2.setText("Contraseña");

        jLabel1.setText("REGISTRAR EMPLEADO");

        txtDir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirActionPerformed(evt);
            }
        });

        lblDir.setText("Direccion");

        txtTlf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTlf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTlfActionPerformed(evt);
            }
        });

        lblDir1.setText("Telefono");

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblDir2.setText("Nombre");

        txtPuesto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblDir3.setText("Puesto");

        jButton1.setText("Crear Usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Sexo");

        cmbSeo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NS", "Masculino", "Femenino" }));
        cmbSeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSeoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(170, 170, 170))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDir)
                        .addGap(18, 18, 18)
                        .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPass2)
                            .addComponent(lblUsuario2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPass3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDir2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDir1)
                                .addGap(18, 18, 18)
                                .addComponent(txtTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(122, 122, 122))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(lblDir3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(225, 225, 225))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmbSeo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerPass)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPass3)
                    .addComponent(txtPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDir1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDir2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDir3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cmbSeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPassActionPerformed

        if (btnVerPass.isSelected()) {
            txtPass2.setEchoChar((char) 0);
        } else {
            txtPass2.setEchoChar('*');
        }

        if (btnVerPass.isSelected()) {
            txtPass.setEchoChar((char) 0);
        } else {
            txtPass.setEchoChar('*');
        }
    }//GEN-LAST:event_btnVerPassActionPerformed

    private void txtPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass2ActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed

    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirActionPerformed

    private void txtTlfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTlfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTlfActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//<editor-fold defaultstate="collapsed" desc="contraseña">
        StringBuffer sb = new StringBuffer();
        char passw[] = txtPass2.getPassword();
        for (int j = 0; j < passw.length; j++) {
            sb.append(passw[j]);
        }
        String password1 = sb.toString();

//</editor-fold>
        String puesto = txtPuesto.getText();
        int cont = 0;
        for (int i = 0; i < txtPuesto.getText().length(); i++) {
            if (Character.isDigit(puesto.charAt(i))) {
                cont++;
            }
        }

        if (password1.equals("")
                || txtDir.getText().equals("")
                || txtNombre.getText().equals("")
                || txtTlf.getText().equals("")
                || txtUsuario.getText().equals("")
                || txtPuesto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Faltan campos por rellenar", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!txtUsuario.getText().contains("admin") || !password1.contains("2019")) {
            JOptionPane.showMessageDialog(null, "Formato de nombre o contraseña incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (cont != txtPuesto.getText().length()) {
            JOptionPane.showMessageDialog(null, "Puesto incorrecto (numérico)", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String sexo = "";
            if (cmbSeo.getSelectedItem().equals("Masculino")) {
                sexo="M";
            } else if (cmbSeo.getSelectedItem().equals("Femenino")) {
                sexo="F";

            }
            emple.setIdEmpleado(txtUsuario.getText());
            emple.setNombre(txtNombre.getText());
            emple.setTelefono(txtTlf.getText());
            emple.setDireccion(txtDir.getText());
            emple.setPuesto(Integer.parseInt(txtPuesto.getText()));

            // realiza la conexión con la BD
            ConectorBD conexion = new ConectorBD();
            String sql = "insert into empleados values( '" + emple.getIdEmpleado()
                    + "','" + emple.getNombre()+sexo
                    + "','" + emple.getTelefono()
                    + "','" + emple.getDireccion()
                    + "','" + emple.getPuesto()
                    + "')";
            String sql2 = "insert into persona values( '" + emple.getIdEmpleado()
                    + "','" + password1
                    + "')";
// recoge el Stament devuelto por la conexión
            try (Statement st = conexion.connec()) {
// para Insertar, Borrar o Modificar. También se puede usar el métod st.execute (sql);
                st.executeUpdate(sql2);
                st.executeUpdate(sql);

                JOptionPane.showMessageDialog(null, "Operación realizada con éxito", "Sentencia SQL",
                        JOptionPane.INFORMATION_MESSAGE);
                txtUsuario.setText("");
                txtDir.setText("");
                txtPass.setText("");
                txtPass2.setText("");
                txtTlf.setText("");
                txtPuesto.setText("");
                txtNombre.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error de operación " + e.getMessage(), "Sentencia SQL", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbSeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSeoActionPerformed


    }//GEN-LAST:event_cmbSeoActionPerformed
/**
 * 
 * @param evt 
 * Comprueba que concuerden las contraseñas.
 */
    private void txtPass2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass2FocusLost
//<editor-fold defaultstate="collapsed" desc="Contraseñas">
        StringBuffer sb = new StringBuffer();
        char passw[] = txtPass.getPassword();
        for (int j = 0; j < passw.length; j++) {
            sb.append(passw[j]);
        }
        String password1 = sb.toString();

        StringBuffer sb2 = new StringBuffer();
        char passw2[] = txtPass2.getPassword();
        for (int f = 0; f < passw2.length; f++) {
            sb2.append(passw2[f]);
        }
        String password2 = sb2.toString();

//</editor-fold>
        if (!password1.equals(password2)) {
            txtPass.setText("");
            txtPass2.setText("");
        }        
    }//GEN-LAST:event_txtPass2FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnVerPass;
    private javax.swing.JComboBox<String> cmbSeo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDir;
    private javax.swing.JLabel lblDir1;
    private javax.swing.JLabel lblDir2;
    private javax.swing.JLabel lblDir3;
    private javax.swing.JLabel lblPass2;
    private javax.swing.JLabel lblPass3;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPass2;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JTextField txtTlf;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
