
package es.ies;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge
 * Variables visibles a la clase.
 */
public class pnlTienda extends javax.swing.JPanel {

    DefaultTableModel modeloProductos = new DefaultTableModel();
    ConectorBD conexion = new ConectorBD();
    Cliente cli = new Cliente();

    /**
     *Genera un pdf.
     */
    public int cantidadNum = 0;
    private String cantidad;
    private String id;
    GenerarPDF gen = new GenerarPDF();

    /**
     *Inicializa la tienda para el cliente.
     */
    public pnlTienda() {
        initComponents();
        generarCliente();
        cli.setNumCompras(0);
        rellenarProductos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntComprar = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bntComprar.setText("Comprar");
        bntComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntComprarActionPerformed(evt);
            }
        });

        btnTicket.setText("Imprimir Ticket");
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(bntComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(bntComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents
/**
 * 
 * @param evt 
 * Conecta con la bbdd e introduce en el fichero pdf párrafos con los datos de cada producto.
 */
    private void bntComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntComprarActionPerformed

        try (Statement st = conexion.connec()) {
            this.id = JOptionPane.showInputDialog("Introduce el ID del producto a comprar");
            this.cantidad = JOptionPane.showInputDialog("Introduce la cantidad");
            cantidadNum = cantidadNum + Integer.parseInt(this.cantidad);
            cli.comprar(cantidadNum);
            cli.participarSorteo(cli.getIdCliente(), cantidadNum);
            String sqlNombre = "select * from productos where id = '" + this.id + "'";
            ResultSet rs = st.executeQuery(sqlNombre);
            rs.next();
            String id = rs.getString("id");
            String nom = rs.getString("nombre");
            String fec = rs.getString("fecha_cad");
            gen.documento.add(new Paragraph(" "));
            gen.documento.add(new Paragraph("Producto: " + id + " Nombre: " + nom
                    + " Fecha de caducidad: " + fec
                    + " Cantidad: " + this.cantidad,
                    FontFactory.getFont("calibri", 12, Font.ITALIC, BaseColor.DARK_GRAY)));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de operación " + e.getMessage(), "Sentencia SQL", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_bntComprarActionPerformed
/**
 * 
 * @param evt 
 * Con la clase Desktop abre el pdf creado.
 */
    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        JLabel lbl = new JLabel("¿Quiere abrir el ticket?");
        JButton btn = new JButton();
        JDialog dia = new JDialog();
        dia.setTitle("Dialogo");
        btn.setBounds(120, 70, 50, 30);
        btn.setText("✓");
        dia.add(btn);
        dia.add(lbl);
        dia.setBounds(550, 300, 200, 150);
        dia.setVisible(true);

        btn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    gen.documento.close();
                    File path = new File("fichero.pdf");
                    Desktop.getDesktop().open(path);
                    dia.setVisible(false);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Error de operación " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });


    }//GEN-LAST:event_btnTicketActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntComprar;
    private javax.swing.JButton btnTicket;
    // End of variables declaration//GEN-END:variables
/**
 * Rellena la tabla de productos devueltos de la bbdd.
 */
    private void rellenarProductos() {
        JTable tablaProductos = new JTable(modeloProductos);
// recoge el Stament devuelto por la conexión
        try (Statement st = conexion.connec()) {
            String sqlProductos = "select ID ,NOMBRE ,TO_CHAR(fecha_cad)\"Fecha de Caducidad\" from productos order by nombre";

            ResultSet rsProductos = st.executeQuery(sqlProductos);
            ResultSetMetaData metaDatosProductos = rsProductos.getMetaData();
            int numeroColumnasP = metaDatosProductos.getColumnCount();
            Object[] etiquetasP = new Object[numeroColumnasP];
            for (int i = 0; i < numeroColumnasP; i++) {
                // Para ResultSetMetaData la primera columna es la 1. 
                etiquetasP[i] = metaDatosProductos.getColumnLabel(i + 1);
            }
            modeloProductos.setColumnIdentifiers(etiquetasP);
            while (rsProductos.next()) {
                Object[] filaP = new Object[numeroColumnasP];  //numeroColumnas es el número de columnas de la tabla y del ResultSet
                for (int i = 0; i < numeroColumnasP; i++) {
                    filaP[i] = rsProductos.getObject(i + 1); // El ResultSet comienza en 1 en vez de en 0
                }
                modeloProductos.addRow(filaP);
            }
            // Se añade al modelo la fila completa.
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de operación " + e.getMessage(), "Sentencia SQL", JOptionPane.ERROR_MESSAGE);
        }
        JScrollPane tbCajaP = new JScrollPane(tablaProductos);
        tbCajaP.setBounds(2, 0, 582, 300);
        this.add(tbCajaP);
        tablaProductos.setEnabled(false);
    }
/**
 * Genera un cliente a partir del id que se logueó (previamente introducido en un fichero
 * lo lee y busca sus datos en la bbdd.
 */
    private void generarCliente() {
        File f2 = new File("nombreCli.txt");

        Lector lee = new Lector(f2);
        String nombreCli = lee.verContenido();

        cli.setIdCliente(nombreCli);
        cli.setNumCompras(cantidadNum);

        try (Statement st = conexion.connec()) {
            String sqlNombre = "select * from clientes where usuario= '" + nombreCli + "'";

            ResultSet rs = st.executeQuery(sqlNombre);
            rs.next();
            String nombre = rs.getString("nombre");
            String tel = rs.getString("telefono");
            String dir = rs.getString("direccion");
            gen.abrir();

            //  File ticket
            gen.documento.addAuthor("Jorge Segade");
            gen.documento.addTitle("Ticket de compra");

            gen.documento.add(new Paragraph("Compra de " + nombreCli,
                    FontFactory.getFont("arial", 22, Font.ITALIC, BaseColor.GRAY)));
            gen.documento.add(new Paragraph("Nombre: " + nombre));
            gen.documento.add(new Paragraph("Telefono: " + tel));
            gen.documento.add(new Paragraph("Direccion: " + dir));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de operación " + e.getMessage(), "Sentencia SQL", JOptionPane.ERROR_MESSAGE);
        }
    }
}
